### ISSUE TITLE
Fix typo in config parameter `checkpoints_period`

### ISSUE THREAD

**Issue by tmpolaczyk** [witnet/witnet-rust#146]
According to the documentation, the following should work:

```toml
[consensus_constants]
checkpoints_period_seconds = 10
```

However, in core/src/config/partial.rs the field name is `checkpoint_period`, missing an `s`, so the following works instead:

```toml
[consensus_constants]
checkpoint_period_seconds = 10
```
