### ISSUE TITLE
Add `enable_sensitive_methods` to the witnet.toml

### ISSUE THREAD

**Issue by Tommytrg** [witnet/witnet-rust#2538]
In the Witnet configuration file, under the `jsonrpc` section, you can enable or disable sensitive methods, such as `sendRequest` or `getPkh` but the parameter name  only appears in the code. To allow users to know about this option, we could add as default `enable_sensitive_methods` to `true` with a comment explaining it.

```toml
[jsonrpc]
enable_sensitive_methods = true
```
