### ISSUE TITLE
`just` should only be a dev-dependency in Cargo.toml

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-rust#575]
We should move `just` out of `dependencies` in Cargo.toml and rather put it in the `dev-dependencies section` (which doesn't exist yet):

```toml
[dev-dependencies]
just = "0.3.13"
```
A pull request solving this issue should also update Cargo.lock so it is consistent with the new configuration.
